-- Migration to add the email_notifications table and its indexes

CREATE TABLE public.email_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  recipient_email TEXT NOT NULL,
  subject TEXT NOT NULL,
  html_content TEXT NOT NULL,
  template_type TEXT NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  metadata JSONB,
  sent_at TIMESTAMPTZ,
  failed_at TIMESTAMPTZ,
  bounced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT email_notifications_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_email_notifications_recipient ON public.email_notifications(recipient_email);
CREATE INDEX idx_email_notifications_status ON public.email_notifications(status);

ALTER TABLE public.email_notifications ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.email_notifications IS 'Stores all outgoing email notifications for tracking and auditing purposes.';
